<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUdd0d0c\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUdd0d0c/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUdd0d0c.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUdd0d0c\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUdd0d0c\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Udd0d0c',
    'container.build_id' => '98b299cf',
    'container.build_time' => 1516627533,
));
