<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8tbcz4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8tbcz4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerY8tbcz4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerY8tbcz4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerY8tbcz4\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Y8tbcz4',
    'container.build_id' => '2cca9b49',
    'container.build_time' => 1516701156,
));
